### ISSUE TITLE
Truncate doesn't work if the element is hidden (using display:none;)

### ISSUE THREAD

**Issue by antonhedstrom** [jeffchan/truncate.js#12]
If the element you are trying to truncate is inside an container that is hidden using display:none; the truncate functionality won't work. This is probably because the while-loop (doing the binary search) is not able to calculate a correct height of the element.

**Comment by jeffchan** [comment]
Correct. I can't think of a way around that, since I need to be able to calculate the height of the element.

**Comment by antonhedstrom** [comment]
I see. Just a thought: Wouldn't it be possible to create like a virtual element (clone the original and set visibility: hidden) for the calculation and then (after the calculation has been done) take that content and insert it into the original element. Of course it will affect performance so I am not sure it you actually want to do that. Just trying to help out :)

Keep it up! :+1:

**Comment by jeffchan** [comment]
Yeah I think that might work in some cases. Having it visibility hidden could be problematic if it interfered with other elements on the page, such as blocking clicks. Thanks for the suggestion though!

**Comment by spectras** [comment]
That would not be reliable though, as the clone, not being at the same spot in the hierarchy, will not have the same CSS rules applied.
I stumbled upon this while seeing the same issue, and came to realize that truncating an element that has `display: none` makes no sense. It is not just that the height cannot be known, it is it does not even have the notion of a height at that time.

**Comment by Tuizi** [comment]
It's true @spectras and also what is the use case to truncate an hidden element? I mean the user don't see it...

If you want to truncate an hidden element, use `visibility:hidden`, it should work as the **visibility** css property keep the height.
Otherwise can you truncate after the element is visible? Put `display:block`, then do the truncate?

**Comment by antonhedstrom** [comment]
I agree with you, my suggested solution is probably to complicated and will not even be a good one. 
Just to clarify: my use case was that I had a shopping cart icon in the top menu of my e-commerce site. If the user clicks the icon a light version of the shopping cart will be shown (basically showing products in cart). I want to truncate the name of the products. Guess I can either use visibility: hidden or truncate when the mini cart is opened. Thanks!

**Comment by Tuizi** [comment]
Your shopping card is in absolute/fixed position?

If yes, it can be visible (display:block or other visual display...) but outside the screen (left=-100% top=-100%) with that truncate will still work for your use case.
