### ISSUE TITLE
Truncation at left or middle of the text

### ISSUE THREAD

**Issue by Tuizi** [jeffchan/truncate.js#15]
I would like to add those features:

Text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eget."

- Truncate at the middle of the text: "Lorem ipsum ... elit. Quisque eget."
- Truncate at the beginning of the text: "... adipiscing elit. Quisque eget."

I don't thing the "More/Less" button feature is useful in this case. 

What do you think?

**Comment by rogeriotaques** [comment]
+1 More flexibility for text truncate would be perfect to cover many cases. :)

**Comment by Tuizi** [comment]
I'm currently working on it, only the "middle" case remains....

**Comment by rogeriotaques** [comment]
@Tuizi cool man!

Any idea about when you'll have it done? I'm currently using a another plugin on a project I'm leading, just because I need the ellipse before the text (on left).

Further, I'd suggest you to make truncate.js identify automatically the lineHeight property, instead of require it to be given over options, if possible. I would be a lot more simple to just call ``` $('.something').truncate()```.

What do you think?

**Comment by Tuizi** [comment]
I can't promise, but **maybe** before the end of this week :)

For the automatic lineHeight property, yes I could definitively do that.

**Comment by rogeriotaques** [comment]
@Tuizi thanks a lot!
Good job, btw. ;)

**Comment by Tuizi** [comment]
@rogeriotaques Still working on it, take me more time than expected :)

**Comment by rogeriotaques** [comment]
@Tuizi no worries. Take your time. :+1:

**Comment by Tuizi** [comment]
Code review in progress, this feature will be in version 1.1 with some limitations and with auto detection of lineHeight

**Comment by rogeriotaques** [comment]
@Tuizi great! Glad to know. :+1: 

I'm just about to fix some issues with the one I'm using now, if review doesn't take so long, I can replace the current by truncate.js. Looking forward to see how it goes. :)

**Comment by Tuizi** [comment]
I'm waiting for @jeffchan to approve my PR. If he can't (doesn't actively working on this library any more), I will merge the PR my self.

Next little PR and feature that will create the version 1.1 is the auto lineHeight detection

**Comment by jeffchan** [comment]
Apologies for the delay. I will take a look today.

**Comment by Tuizi** [comment]
Feature added with #20 
Will be available in truncate.js version 1.1

**Comment by rogeriotaques** [comment]
Good job guys! Thank you very much!
Let me test it and I let you know any update. 👍

**Comment by rogeriotaques** [comment]
@Tuizi good job. It's working nicely. 👍 👍 👍

**Comment by Tuizi** [comment]
Thank. Don't hesitate to add issues when you find some and/or ask for
features
On Apr 12, 2016 2:16 AM, "Rogério Taques" <notifications@github.com> wrote:

@Tuizi <https://github.com/Tuizi> good job. It's working nicely. 👍 👍 👍

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/jeffchan/truncate.js/issues/15#issuecomment-208725348>
