### ISSUE TITLE
Update this library with 2016 web "standards" (bower, npm, markdown, ...)

### ISSUE THREAD

**Issue by Tuizi** [jeffchan/truncate.js#16]
I would like to add those features:

1. Use npm instead of a make file: It's common to every package those days, and npm is crossplatform, easier for Windows developers to collaborate on this repository
2. Make this package a bower package: http://bower.io/docs/creating-packages/#register
3. Use grunt builder instead of make file (minify, concat, jshint, etc...) (same reason as point 1)
4. Use markdown instead of text file (GitHub standard, reformat document, etc...), including  #9 

What do you think

**Comment by jeffchan** [comment]
1. I think I agree. Not religious about the Makefile
2. It seems like the community is moving towards `npm`. https://gofore.com/ohjelmistokehitys/stop-using-bower/ 
3. I personally prefer to use gulp/webpack -- happy to take a PR for this.
4. I merged #9 

Unfortunately I'm not actively using this, so I'm happy to accept PR's or add you as a contributor.

**Comment by Tuizi** [comment]
Yes I would like to be a contributor :). I'm actively using this library!

1. :+1: 
2. Yes, it's true so no bower
3. I will use gulp (webpack is overkill for a tiny library)
4. :+1:
