### ISSUE TITLE
$().truncate('update', value) seems not to be working if value is null or empty string

### ISSUE THREAD

**Issue by flaviooliveri** [jeffchan/truncate.js#23]
$().truncate('update', value) seems not to be working if value is null or empty string.
plnkr with the problem: https://plnkr.co/edit/xyB0ebqwgvjq6D855fDA

**Comment by Tuizi** [comment]
Good catch @flaviooliveri !

I will work on it and let you know when the fix will be available

**Comment by Tuizi** [comment]
Hey @flaviooliveri . The bug is fixed and will be available in the version 1.1.1.
Check the PR #24 for the fix detail. I will wait for @jeffchan to review it before publising the version 1.1.1 on **npm**

**Comment by skaor** [comment]
Update function seems to have a problem with long text... (Same issue in 1.1.0)
https://plnkr.co/edit/jVSCVD1yqhzGNWVZlFo1?
