### ISSUE TITLE
Compute line height if `options.lineHeight` is not provided

### ISSUE THREAD

**Issue by aron** [jeffchan/truncate.js#3]
Should be able to use `$root.css('line-height')` for a best guess right?

**Comment by NoxHarmonium** [comment]
Or as a non jQuery dependent solution something like this might do:

``` 
var style = window.getComputedStyle(el, null);
var lineHeight = parseFloat(style['line-height'])
```

Is it a required parameter for performance reasons or something? If I submitted a pull request to make line height optional and auto-detected if not provided would it be accepted?

**Comment by jeffchan** [comment]
Yes definitely would consider it! Just got to make sure it's cross browser compliant

**Comment by Tuizi** [comment]
getComputedStyle is one of the most expensive javascript property. This will kill rendering performance on a page using 100+ truncation.

**Comment by Tuizi** [comment]
@NoxHarmonium @aron feature available in truncate.js v1.1.0, enjoy!

**Comment by jeffchan** [comment]
thank you @Tuizi !

**Comment by NoxHarmonium** [comment]
Nice work :+1:
