### ISSUE TITLE
Using $.trim in truncateTextContent removes whitespace in text.

### ISSUE THREAD

**Issue by stubenbaines** [jeffchan/truncate.js#8]
Was wondering if using $.trim is necessary in the function truncateTextContent:
chunk = $.trim(original.substr(0, mid + 1)) + options.ellipsis;

The problem I'm seeing is with content that has anchor tags in them. The text node after the anchor tag loses any leading whitespace which affects display. So you'd have something like this:

Some text <a href="/foo">with some link</a> and some more text.

get converted into
Some text <a href="/foo">with some link</a>and some...

on truncation.

**Comment by jeffchan** [comment]
I believe it was originally necessary because sometimes there is unnecessary white space from the HTML markup. One way to fix this is to only trim if we have extra whitespace.

**Comment by Tuizi** [comment]
@stubenbaines I know it's an old request, but I could fix this issue

**Comment by Tuizi** [comment]
Will be fixed in **version 1.1.2**
